# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['ordering']},
        ),
    ]
